---
apiVersion: v1
kind: ConfigMap

metadata:
    name: api-env

data:
    PORT: "8281"
    SERVICE_CHECK_URL: unset
    HEALTH_CHECK_URL: unset
    BUILD_INFO_PATH: /app/build-info.json
    SERVICE_REGISTRATION_URL: "http://consul.sweetrpg-support.svc.cluster.local:1234"
    # SERVER_NAME: dev.sweetrpg.com
    JAEGER_SERVICE_NAME: api.sweetrpg-catalog
    JAEGER_SAMPLER_TYPE: ratelimiting
    JAEGER_SAMPLER_PARAM: "1"
    JAEGER_PROPAGATION: b3
    JAEGER_ENDPOINT: http://jaeger-collector.istio-system.svc.cluster.local:14268/api/traces
