---
apiVersion: v1
kind: ConfigMap

metadata:
    name: api-env

data:
    SERVICE_CHECK_URL: unset
    HEALTH_CHECK_URL: unset
    BUILD_INFO_PATH: /app/build-info.json
    SERVICE_REGISTRATION_URL: "http://consul.sweetrpg-support.svc.cluster.local:1234"
    JAEGER_SERVICE_NAME: api.sweetrpg-catalog
    JAEGER_SAMPLER_TYPE: ratelimiting
    JAEGER_SAMPLER_PARAM: "1"
    JAEGER_PROPAGATION: b3
    JAEGER_ENDPOINT: http://jaeger-collector.observability.svc.cluster.local:9411/api/v2/spans
    OTEL_EXPORTER_OTLP_ENDPOINT: http://otlp-collector.observability.svc.cluster.local:4317/
    SENTRY_RELEASE: "dev"
