---
apiVersion: core.openfeature.dev/v1beta1
kind: FeatureFlag

metadata:
  name: flags

spec:
  flagSpec:
    flags:
      test:
        state: "ENABLED"
        variants:
        bar: "BAR"
        baz: "BAZ"
        defaultVariant: "bar"
