---
apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: api-v1
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.middlewares: sweetrpg-catalog-strip-prefix-v1@kubernetescrd
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prd

spec:
  ingressClassName: traefik
  rules:
    - host: api.catalog.dev.sweetrpg.com
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: api-v1
                port:
                  name: http
  tls:
    - hosts:
        - api.catalog.dev.sweetrpg.com
      secretName: catalog-api-v1-tls
