# ---
# apiVersion: traefik.containo.us/v1alpha1
# kind: IngressRoute

# metadata:
#   name: api-v1

# spec:
#   entryPoints:
#     - web
#   routes:
#     - match: Host(`api.catalog.dev.sweetrpg.com`) && (PathPrefix(`/0/`) || PathPrefix(`/1/`))
#       kind: Rule
#       services:
#         - kind: Service
#           name: api-v1
#           port: 8281
#           passHostHeader: true
#           responseForwarding:
#             flushInterval: 1ms
#       middlewares:
#         - name: strip-prefix
#
---
apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: api-v1
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prd

spec:
  rules:
    - host: catalog.api.dev.sweetrpg.com
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: api-v1
                port:
                  number: 8281
  tls:
    - hosts:
        - catalog.api.dev.sweetrpg.com
      secretName: api-v1-tls
