apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sweetrpg-catalog

resources:
    - ../../base
    - atlas-db-user.yaml
    - configmaps.yaml
    - ingress.yaml
    - middlewares.yaml
    - password.yaml
    - pod-monitor.yaml
    - secrets/auth.yaml
    - secrets/cache.yaml
    - secrets/db.yaml
    - secrets/files.yaml
    - secrets/misc.yaml

labels:
    - pairs:
          app: api
          version: v1
          platform: sweetrpg
          package: catalog
          component: api

generatorOptions:
    disableNameSuffixHash: true
