---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sweetrpg-catalog

resources:
    - ../../base
    - configmaps.yaml
    - hpa.yaml
    - pdb.yaml
    - mongodb-atlas-service-entry.yaml
    # - destination-rules.yaml
    - secrets.yaml
    # - virtual-service.yaml
    - ingress.yaml

commonLabels:
    app: api
    version: v1
    platform: sweetrpg
    package: catalog
    component: api

generatorOptions:
    disableNameSuffixHash: true
