---
apiVersion: policy/v1
kind: PodDisruptionBudget

metadata:
    name: api-v1

spec:
    minAvailable: 1
    selector:
        matchLabels:
            platform: sweetrpg
            app: api
            package: catalog
            component: api
            version: v1
