---
development:
  dialect: postgres
  database: catalog_api_development
  user: catalog_api
  password: catalog_api
  host: 127.0.0.1
  pool: 5

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://catalog_api:catalog_api@127.0.0.1:5432/catalog_api_test?sslmode=disable"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://catalog_api:catalog_api@127.0.0.1:5432/catalog_api_production?sslmode=disable"}}
