---
apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
    name: catalog-api-auth

spec:
    refreshInterval: "1h"
    secretStoreRef:
        name: akeyless
        kind: ClusterSecretStore
    target:
        name: api-auth
        creationPolicy: Owner
    dataFrom:
        - extract:
              key: Auth0
