---
apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
    name: catalog-api-nats

spec:
    refreshInterval: 1h
    secretStoreRef:
        name: akeyless
        kind: ClusterSecretStore
    target:
        name: api-nats
        creationPolicy: Owner
    data:
        - secretKey: NATS_USER
          remoteRef:
              key: /sweetrpg/catalog-api/nats/auth
              property: username
        - secretKey: NATS_PASSWORD
          remoteRef:
              key: /sweetrpg/catalog-api/nats/auth
              property: password
