---
kind: Service
apiVersion: v1

metadata:
    name: api-v1

spec:
    selector:
        app: api
        version: v1
        platform: sweetrpg
        package: catalog
        component: api
    type: LoadBalancer
    ports:
        - name: http
          port: 8281
          targetPort: http
