apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sweetrpg-catalog

resources:
    - ../../base
    - configmaps.yaml
    - secrets.yaml
    - ingress.yaml
    - middlewares.yaml

labels:
    - pairs:
          app.kubernetes.io/name: catalog-api
          app.kubernetes.io/version: v1
          app.kubernetes.io/component: api
          app.kubernetes.io/part-of: catalog
          com.sweetrpg/env: local
      includeSelectors: false
      includeTemplates: true

generatorOptions:
    disableNameSuffixHash: true

images:
    - name: catalog-api
      newName: ghcr.io/sweetrpg/catalog-api
      newTag: v0.2.2
