basePath: /
host: localhost:8000
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: Testing Swagger APIs.
  license:
    name: MIT
    url: https://mit-license.org/
  termsOfService: http://swagger.io/terms/
  title: Catalog API service
  version: "1.0"
paths:
  /contributions:
    get:
      description: Lists the contributions in the database.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: List contributions
      tags:
      - contributions
  /contributions/{id}:
    get:
      description: Get the details of a contribution from the database.
      parameters:
      - description: Contribution ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
          schema: {}
        "404":
          description: Not Found
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: Get a contribution
      tags:
      - contributions
  /licenses:
    get:
      description: Lists the licenses in the database.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: List licenses
      tags:
      - licenses
  /licenses/{id}:
    get:
      description: Get the details of a license from the database.
      parameters:
      - description: License ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
          schema: {}
        "404":
          description: Not Found
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: Get a license
      tags:
      - licenses
  /licenses/{id}/volumes:
    get:
      description: Gets all the volumes associated with a particular license
      parameters:
      - description: License ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
          schema: {}
        "404":
          description: Not Found
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: Get license volumes
      tags:
      - licenses
  /persons:
    get:
      description: Lists the persons in the database.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: List persons
      tags:
      - persons
  /persons/{id}:
    get:
      description: Get the details of a person from the database.
      parameters:
      - description: Person ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
          schema: {}
        "404":
          description: Not Found
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: Get a person
      tags:
      - persons
  /publishers:
    get:
      description: Lists the publishers in the database.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: List publishers
      tags:
      - publishers
  /publishers/{id}:
    get:
      description: Get the details of a publisher from the database.
      parameters:
      - description: Publisher ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
          schema: {}
        "404":
          description: Not Found
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: Get a publisher
      tags:
      - publishers
  /reviews:
    get:
      description: Lists the reviews in the database.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: List reviews
      tags:
      - reviews
  /reviews/{id}:
    get:
      description: Get the details of a review from the database.
      parameters:
      - description: Review ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
          schema: {}
        "404":
          description: Not Found
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: Get a review
      tags:
      - reviews
  /status/health:
    get:
      description: Health check
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema: {}
      summary: Health check
      tags:
      - status
  /status/ping:
    get:
      description: Ping
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema: {}
      summary: Ping
      tags:
      - status
  /studios:
    get:
      description: Lists the studios in the database.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: List studios
      tags:
      - studios
  /studios/{id}:
    get:
      description: Get the details of a studio from the database.
      parameters:
      - description: Studio ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
          schema: {}
        "404":
          description: Not Found
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: Get a studio
      tags:
      - studios
  /systems:
    get:
      description: Lists the systems in the database.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: List systems
      tags:
      - systems
  /systems/{id}:
    get:
      description: Get the details of a system from the database.
      parameters:
      - description: System ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
          schema: {}
        "404":
          description: Not Found
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: Get a system
      tags:
      - systems
  /volumes:
    get:
      description: Lists the volumes in the database.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: List volumes
      tags:
      - volumes
  /volumes/{id}:
    get:
      description: Get the details of a volume from the database.
      parameters:
      - description: Volume ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
          schema: {}
        "404":
          description: Not Found
          schema: {}
        "500":
          description: Internal Server Error
          schema: {}
      summary: Get a volume
      tags:
      - volumes
schemes:
- http
- https
swagger: "2.0"
