name: PR Validation

on:
  pull_request:
    branches:
      - master
      - develop

permissions:
  contents: read

jobs:
  validate:
    uses: sweetrpg/github-actions/.github/workflows/go-ci.yaml@3-add-code-coverage
    with:
      publish-coverage: false
    secrets: inherit
