name: Go CI

concurrency: ci-${{ github.ref }}

on:
    push:
        branches: [develop]
        paths:
            - "src/**"
    workflow_dispatch:

jobs:
    tests:
        name: ${{ matrix.name }}
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                include:
                    - {
                          name: Linux,
                          python: "1.23",
                          os: ubuntu-latest,
                      }
        steps:
            - uses: actions/checkout@v4
            - name: tests
              run: echo "TODO"

    #    docs:
    #        needs: [tests]
    #        runs-on: ubuntu-latest
    #        concurrency: docs
    #        steps:
    #            - uses: actions/checkout@v4
    #            - uses: actions/setup-python@v5
    #              with:
    #                  python-version: "3.11"
    #            - name: install-deps
    #              run: pip install -r requirements/docs.txt
    #            - name: make-docs
    #              run: cd docs && make html
    #            - name: publish-docs
    #              uses: peaceiris/actions-gh-pages@v3
    #              with:
    #                  github_token: ${{ secrets.GITHUB_TOKEN }}
    #                  publish_dir: ./docs/_build/html

    tag:
        needs: [tests]
        runs-on: ubuntu-latest
        concurrency: publish
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            # - name: publish
            #   uses: relekang/python-semantic-release@v7.34.6
            #   with:
            #       additional_options: "--patch"
            #       github_token: ${{ secrets.GITHUB_TOKEN }}
            #       repository_username: __token__
            #       repository_password: ${{ secrets.PYPI_TOKEN }}
